// Generated by https://quicktype.io

import { SeedSale } from "./seed.sale.interface";

export interface SeedSalesResponse {
  seed_sales: SeedSale[];
  pagination: Pagination;
}

export interface Pagination {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}


