import { CampaignSalesResponse } from "@/interfaces/sales/campaign.sales.response";

export const mockDeliverySalesData: CampaignSalesResponse = {
  campaigns: [
    {
      campaign_id: 1,
      campaign_name: "24/25",
      crops: [
        {
          userId: 1,
          campaign_id: 1,
          campaign_name: "24/25",
          crop_name_id: 2,
          crop_name: "Maíz",
          seed_deliveries: [
            {
              id: 35,
              userId: 1,
              campaign_id: 1,
              campaign_name: "24/25",
              crop_name_id: 2,
              crop_name: "Maíz",
              tn_sold: 50,
              tn_delivered: 80,
              waybill_number: "CP-MAI-001",
              destination: "AGD",
              status: "partial",
              delivery_date: "2026-01-19",
              deleted_at: null,
              created_at: "2026-01-19 16:08:40",
              updated_at: "2026-01-19 16:08:40",
            },
            {
              id: 36,
              userId: 1,
              campaign_id: 1,
              campaign_name: "24/25",
              crop_name_id: 2,
              crop_name: "Maíz",
              tn_sold: 0,
              tn_delivered: 80,
              waybill_number: "CP-MAI-002",
              destination: "AGD",
              status: "partial",
              delivery_date: "2026-01-25",
              deleted_at: null,
              created_at: "2026-01-25 12:20:27",
              updated_at: "2026-01-25 12:20:27",
            },
          ],
          seed_sales: [
            {
              id: 48,
              userId: 1,
              campaign_id: 1,
              campaign_name: "24/25",
              crop_name_id: 2,
              crop_name: "Maíz",
              primary_liquidation_number: "LP-MAI-001",
              destination: "Buenos Aires",
              tn_sold: 50,
              price_per_tn: 100,
              sale_date: "2026-01-19",
              deleted_at: null,
              created_at: "2026-01-19 16:08:40",
              updated_at: "2026-01-25 11:41:50",
            },
            {
              id: 49,
              userId: 1,
              campaign_id: 1,
              campaign_name: "24/25",
              crop_name_id: 2,
              crop_name: "Maíz",
              primary_liquidation_number: "LP-MAIZ-001",
              destination: "AGD",
              tn_sold: 50,
              price_per_tn: 150,
              sale_date: "2026-01-25",
              deleted_at: null,
              created_at: "2026-01-25 12:18:26",
              updated_at: "2026-01-25 12:18:26",
            },
          ],
        },
        {
          userId: 1,
          campaign_id: 1,
          campaign_name: "24/25",
          crop_name_id: 5,
          crop_name: "Girasol",
          seed_deliveries: [
            {
              id: 32,
              userId: 1,
              campaign_id: 1,
              campaign_name: "24/25",
              crop_name_id: 5,
              crop_name: "Girasol",
              tn_sold: 50,
              tn_delivered: 75,
              waybill_number: "CP-GIRASOL-1",
              destination: "Suardi",
              status: "partial",
              delivery_date: "2026-01-17",
              deleted_at: null,
              created_at: "2026-01-17 17:58:51",
              updated_at: "2026-01-19 16:07:45",
            },
          ],
          seed_sales: [
            {
              id: 35,
              userId: 1,
              campaign_id: 1,
              campaign_name: "24/25",
              crop_name_id: 5,
              crop_name: "Girasol",
              primary_liquidation_number: "LP-2026-02",
              destination: "Buenos Aires",
              tn_sold: 50,
              price_per_tn: 150,
              sale_date: "2026-01-17",
              deleted_at: null,
              created_at: "2026-01-17 17:58:51",
              updated_at: "2026-01-25 11:42:03",
            },
            {
              id: 47,
              userId: 2,
              campaign_id: 1,
              campaign_name: "24/25",
              crop_name_id: 5,
              crop_name: "Girasol",
              primary_liquidation_number: "LP-GIR-001",
              destination: "Buenos Aires",
              tn_sold: 20,
              price_per_tn: 100,
              sale_date: "2026-01-19",
              deleted_at: null,
              created_at: "2026-01-19 12:38:15",
              updated_at: "2026-01-25 11:41:57",
            },
          ],
        },
      ],
    },
    {
      campaign_id: 2,
      campaign_name: "23/24",
      crops: [
        {
          userId: 1,
          campaign_id: 2,
          campaign_name: "23/24",
          crop_name_id: 1,
          crop_name: "Soja",
          seed_deliveries: [
            {
              id: 20,
              userId: 1,
              campaign_id: 2,
              campaign_name: "23/24",
              crop_name_id: 1,
              crop_name: "Soja",
              tn_sold: 100,
              tn_delivered: 100,
              waybill_number: "CP-SOJA-001",
              destination: "Rosario",
              status: "complete",
              delivery_date: "2025-06-15",
              deleted_at: null,
              created_at: "2025-06-15 10:00:00",
              updated_at: "2025-06-15 10:00:00",
            },
          ],
          seed_sales: [
            {
              id: 30,
              userId: 1,
              campaign_id: 2,
              campaign_name: "23/24",
              crop_name_id: 1,
              crop_name: "Soja",
              primary_liquidation_number: "LP-SOJA-001",
              destination: "Rosario",
              tn_sold: 100,
              price_per_tn: 320,
              sale_date: "2025-06-15",
              deleted_at: null,
              created_at: "2025-06-15 10:00:00",
              updated_at: "2025-06-15 10:00:00",
            },
          ],
        },
      ],
    },
  ],
  pagination: {
    page: 1,
    limit: 10,
    total: 2,
    totalPages: 1,
  },
};
